plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/tan/Documents/code/ui-test/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build:all"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]